# More Data Manipulation
## Introduction to Pandas

> **Disclaimer:** This notebook was generated with the assistance of AI and has been human-reviewed for accuracy and quality.

**Topics Covered:**
- Pandas Dataframe Creation
- Simple Method Calls
- Indexing
- Modification in Place

---

## 1. What is Pandas — and Why Does It Matter?

**Pandas** is a Python library built for working with structured, tabular data — the kind of data you'd normally see in a spreadsheet or a database table. It was created in 2008 by Wes McKinney while he was working in finance, and it has since become the **default tool for data manipulation** across virtually every field that works with data.

### Why is Pandas so widespread?

| Field | How Pandas is Used |
|---|---|
| Finance | Analyzing stock prices, returns, risk calculations |
| Healthcare | Patient records, clinical trial data, outcomes analysis |
| Marketing | Customer segmentation, campaign performance, A/B testing |
| Sports Analytics | Player stats, game logs, performance trends |
| Machine Learning | Cleaning and preparing datasets before modeling |
| Journalism | Investigating public datasets, census data, government records |

The reason Pandas is everywhere is simple: **almost all real-world data is tabular**, and Pandas gives you a powerful, expressive toolkit to load, clean, reshape, filter, and summarize that data — all in a few lines of Python.

---

## The Two Core Data Structures

Before using Pandas, you need to understand its two fundamental building blocks:

### 1. `Series` — A single column of data
A **Series** is a one-dimensional labeled array. Think of it as a single column from a spreadsheet, with an index (row labels) on the left and values on the right.

### 2. `DataFrame` — A full table of data
A **DataFrame** is a two-dimensional table made up of multiple Series sharing the same index. Think of it as a full spreadsheet — rows and columns, each column being a Series.

In [ ]:
import pandas as pd

# ─────────────────────────────────────────────
# PART 1: Series
# A Series is a single column of labeled data.
# ─────────────────────────────────────────────

# Creating a Series from a plain Python list
temperatures = pd.Series([72, 68, 75, 80, 65], name="Temperature (°F)")
print("=== Series ===")
print(temperatures)

=== Series ===
0    72
1    68
2    75
3    80
4    65
Name: Temperature (°F), dtype: int64

In [4]:
# ─────────────────────────────────────────────
# PART 2: DataFrame
# A DataFrame is a table — a collection of
# Series that share the same index.
# ─────────────────────────────────────────────

# Creating a DataFrame from a dictionary
# Each key becomes a column name; each list becomes that column's values
data = {
    "Name":       ["Alice", "Bob", "Carmen", "David", "Eva"],
    "Age":        [28, 34, 22, 45, 30],
    "Department": ["Engineering", "Marketing", "Engineering", "HR", "Marketing"],
    "Salary":     [95000, 72000, 88000, 61000, 78000]
}

df = pd.DataFrame(data)
print("=== DataFrame ===")
print(df)

=== DataFrame ===
     Name  Age   Department  Salary
0   Alice   28  Engineering   95000
1     Bob   34    Marketing   72000
2  Carmen   22  Engineering   88000
3   David   45           HR   61000
4     Eva   30    Marketing   78000

---

## 2. Pandas Usage

### 2.a Loading Data from a File

In real life, you will almost never type your data directly into Python.

Instead, data usually comes from somewhere else — a file on your computer, a database, a website, or a shared drive. The most common format you will encounter is a **CSV file** (short for *Comma-Separated Values*). It is a plain text file where each row is a record and each column is separated by a comma.

Pandas makes loading a CSV file extremely simple with a single function:

```python
pd.read_csv("your_file.csv")
```

---

### The Dataset: FY2026 Fair Market Rents

In the same folder as this notebook, there is a file called **FY2026.csv**.

This dataset comes from the U.S. Department of Housing and Urban Development (HUD). Every year, HUD publishes **Fair Market Rents (FMRs)** — estimates of what it costs to rent a modest apartment in counties and metro areas across the entire country. These numbers are used to determine housing assistance for low-income families.

A subset of columns in this dataset are:

| Column | Description |
|---|---|
| `stusps` | State abbreviation (e.g. NY, TX) |
| `countyname` | Name of the county |
| `pop2023` | 2023 population estimate |
| `fmr_0` | Fair Market Rent — Studio (0 bedrooms) |
| `fmr_1` | Fair Market Rent — 1 bedroom |
| `fmr_2` | Fair Market Rent — 2 bedrooms |
| `fmr_3` | Fair Market Rent — 3 bedrooms |
| `fmr_4` | Fair Market Rent — 4 bedrooms |

In [6]:
import pandas as pd

# Load the CSV file into a DataFrame
# The file is in the same folder as this notebook, so we just use the file name
rent_df = pd.read_csv("FY2026.csv")

rent_df

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,AL,1,METRO33860M33860,Autauga County,NaN,1,"Montgomery, AL MSA",100199999,58761,860,870,1016,1304,1537
1,AL,1,METRO19300M19300,Baldwin County,NaN,1,"Daphne-Fairhope-Foley, AL MSA",100399999,233420,1094,1200,1345,1692,2171
2,AL,1,NCNTY01005N01005,Barbour County,NaN,0,"Barbour County, AL",100599999,24877,576,693,776,1017,1068
3,AL,1,METRO13820M13820,Bibb County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100799999,22251,1024,1155,1266,1583,1801
4,AL,1,METRO13820M13820,Blount County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100999999,59077,1024,1155,1266,1583,1801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4759,PR,72,METRO41980MM7440,Yabucoa Municipio,NaN,1,"San Juan-Guaynabo, PR HUD Metro FMR Area",7215199999,30313,559,572,663,868,1046
4760,PR,72,METRO38660M49500,Yauco Municipio,NaN,1,"Yauco, PR HUD Metro FMR Area",7215399999,33988,423,443,486,664,673
4761,VI,78,NCNTY78010N78010,St. Croix,NaN,0,"St. Croix Island, VI",7801099999,53234,1002,1023,1249,1504,1656
4762,VI,78,NCNTY78020N78020,St. John,NaN,0,"St. John Island, VI",7802099999,4197,1563,1578,1969,2362,2607
4763,VI,78,NCNTY78030N78030,St. Thomas,NaN,0,"St. Thomas Island, VI",7803099999,51181,1024,1189,1467,1759,1942

---

### 2.b Common Pandas Methods

#### The Pattern: Object . Method ( )

This should look familiar — it is the same pattern from **Object Oriented Programming**.

A DataFrame is an **object**. It has data stored inside it, and it comes with built-in **methods** that let you interact with that data. You call those methods using dot notation:

```
dataframe_name . method_name( )
       ↑                ↑
   the object       the action
```

For example:
```python
rent_df.head()      # call the head method on the rent_df object
rent_df.describe()  # call the describe method on the rent_df object
```

You already used this in regular Python — for example, `my_list.append(5)` or `my_string.upper()`. Pandas DataFrames follow the exact same idea. The object just happens to be a table of data.

---

### Methods We Will Cover

| Method | What It Does |
|---|---|
| `df.head()` | Shows the first N rows of the DataFrame (default is 5) |
| `df.describe()` | Prints summary statistics for all numeric columns |
| `df.info()` | Prints column names, data types, and non-null counts |
| `df.dropna()` | Returns a new DataFrame with all rows containing missing values removed |

In [8]:
# ── df.head() ──────────────────────────────────────────────────────────────
# Shows the first rows of the DataFrame.
# By default it shows 5 rows, but you can pass a number to change that.

rent_df.head()

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,AL,1,METRO33860M33860,Autauga County,NaN,1,"Montgomery, AL MSA",100199999,58761,860,870,1016,1304,1537
1,AL,1,METRO19300M19300,Baldwin County,NaN,1,"Daphne-Fairhope-Foley, AL MSA",100399999,233420,1094,1200,1345,1692,2171
2,AL,1,NCNTY01005N01005,Barbour County,NaN,0,"Barbour County, AL",100599999,24877,576,693,776,1017,1068
3,AL,1,METRO13820M13820,Bibb County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100799999,22251,1024,1155,1266,1583,1801
4,AL,1,METRO13820M13820,Blount County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100999999,59077,1024,1155,1266,1583,1801

In [9]:
rent_df.head(10)

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,AL,1,METRO33860M33860,Autauga County,NaN,1,"Montgomery, AL MSA",100199999,58761,860,870,1016,1304,1537
1,AL,1,METRO19300M19300,Baldwin County,NaN,1,"Daphne-Fairhope-Foley, AL MSA",100399999,233420,1094,1200,1345,1692,2171
2,AL,1,NCNTY01005N01005,Barbour County,NaN,0,"Barbour County, AL",100599999,24877,576,693,776,1017,1068
3,AL,1,METRO13820M13820,Bibb County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100799999,22251,1024,1155,1266,1583,1801
4,AL,1,METRO13820M13820,Blount County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100999999,59077,1024,1155,1266,1583,1801
5,AL,1,NCNTY01011N01011,Bullock County,NaN,0,"Bullock County, AL",101199999,10328,576,708,776,930,1302
6,AL,1,NCNTY01013N01013,Butler County,NaN,0,"Butler County, AL",101399999,18981,622,638,837,1004,1139
7,AL,1,METRO11500M11500,Calhoun County,NaN,1,"Anniston-Oxford, AL MSA",101599999,116162,753,757,962,1300,1361
8,AL,1,NCNTY01017N01017,Chambers County,NaN,0,"Chambers County, AL",101799999,34612,691,770,1002,1265,1327
9,AL,1,NCNTY01019N01019,Cherokee County,NaN,0,"Cherokee County, AL",101999999,25069,627,682,844,1012,1259

In [10]:
# ── df.describe() ──────────────────────────────────────────────────────────
# Prints summary statistics for every numeric column:
# count, mean, min, max, and the 25 / 50 / 75 percentiles.
# Great for getting a quick feel for the range and spread of your data.

rent_df.describe()

,state,metro,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
count,4764.000000,4764.000000,4.764000e+03,4.764000e+03,4764.000000,4764.000000,4764.000000,4764.000000,4764.000000
mean,30.374055,0.414777,3.045416e+09,7.026966e+04,1014.909320,1089.795970,1349.301637,1738.247691,1972.116289
std,15.052888,0.492735,1.506162e+09,2.724923e+05,381.833631,409.866429,494.510254,606.266187,682.418703
min,1.000000,0.000000,1.002000e+08,0.000000e+00,407.000000,410.000000,475.000000,621.000000,639.000000
25%,21.000000,0.000000,2.107350e+09,3.969250e+03,729.000000,778.000000,973.000000,1270.000000,1450.000000
50%,27.000000,0.000000,2.711300e+09,1.492550e+04,922.500000,987.000000,1224.000000,1625.000000,1812.000000
75%,42.500000,1.000000,4.260076e+09,4.180750e+04,1219.000000,1302.000000,1616.000000,2087.000000,2451.000000
max,78.000000,1.000000,7.803100e+09,9.936690e+06,3179.000000,3298.000000,4214.000000,5377.000000,5659.000000

In [12]:
# ── df.info() ──────────────────────────────────────────────────────────────
# Prints a compact overview of the whole DataFrame:
#   - total number of rows
#   - each column's name
#   - how many non-null (non-missing) values it has
#   - the data type of each column  (int, float, object, etc.)
rent_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4764 entries, 0 to 4763
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   stusps            4764 non-null   str
 1   state             4764 non-null   int64
 2   hud_area_code     4764 non-null   str
 3   countyname        4764 non-null   str
 4   county_town_name  1604 non-null   str
 5   metro             4764 non-null   int64
 6   hud_area_name     4764 non-null   str
 7   fips              4764 non-null   int64
 8   pop2023           4764 non-null   int64
 9   fmr_0             4764 non-null   int64
 10  fmr_1             4764 non-null   int64
 11  fmr_2             4764 non-null   int64
 12  fmr_3             4764 non-null   int64
 13  fmr_4             4764 non-null   int64
dtypes: int64(9), str(5)
memory usage: 521.2 KB

In [ ]:
# ── df.dropna() ────────────────────────────────────────────────────────────
# Returns a NEW DataFrame where every row that had at least one
# missing value has been removed.
# The original rent_df is NOT changed — dropna() gives you a clean copy.

clean_df = rent_df.dropna()

print("--- rent_df.dropna() ---")
print("Rows before dropna:", len(rent_df))
print("Rows after  dropna:", len(clean_df))

--- rent_df.dropna() ---
Rows before dropna: 4764
Rows after  dropna: 1604

In [16]:
print("First 5 rows of the cleaned DataFrame:")
clean_df.head()

First 5 rows of the cleaned DataFrame:

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
309,CT,9,METRO25540M25540,Capitol Planning Region,Andover town,1,"Hartford-West Hartford-East Hartford, CT MSA",911001080,3148,1286,1477,1865,2236,2537
310,CT,9,METRO25540M25540,Capitol Planning Region,Avon town,1,"Hartford-West Hartford-East Hartford, CT MSA",911002060,18856,1286,1477,1865,2236,2537
311,CT,9,METRO25540M25540,Capitol Planning Region,Berlin town,1,"Hartford-West Hartford-East Hartford, CT MSA",911004300,20210,1286,1477,1865,2236,2537
312,CT,9,METRO25540M25540,Capitol Planning Region,Bloomfield town,1,"Hartford-West Hartford-East Hartford, CT MSA",911005910,21547,1286,1477,1865,2236,2537
313,CT,9,METRO25540M25540,Capitol Planning Region,Bolton town,1,"Hartford-West Hartford-East Hartford, CT MSA",911006260,4848,1286,1477,1865,2236,2537

---

### 2.c Method Chaining

**Method chaining** is when you call one method directly on the result of another method — all in a single line.

The pattern looks like this:

```
dataframe . first_method( ) . second_method( )
```

This works because the first method returns an object, and that object immediately has the second method called on it. You never need to store the in-between result in a variable.

You have already seen this in regular Python:

```python
"  hello world  ".strip().upper()
```

Here, `.strip()` removes the whitespace and returns a new string, then `.upper()` is called on that result. Pandas works the exact same way.

---

### Example: `.isna().sum()`

- **`.isna()`** — goes through every cell in the DataFrame and returns `True` if the value is missing (`NaN`), and `False` if it is not
- **`.sum()`** — adds up all the `True` values column by column (remember: `True` counts as `1`, `False` as `0`)

Chained together, `rent_df.isna().sum()` gives you a count of missing values for every column in one step.

*(Note: student-authored code follows below.)*

In [17]:
# Step 1 alone: .isna() returns a DataFrame of True/False values
rent_df.isna()

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4759,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4760,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4761,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4762,False,False,False,False,True,False,False,False,False,False,False,False,False,False
4763,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [19]:
# Step 2: chain .sum() onto .isna() to count the missing values per column
rent_df.isna().sum()

stusps                 0
state                  0
hud_area_code          0
countyname             0
county_town_name    3160
metro                  0
hud_area_name          0
fips                   0
pop2023                0
fmr_0                  0
fmr_1                  0
fmr_2                  0
fmr_3                  0
fmr_4                  0
dtype: int64

---

## 3. Cleaning Data in Pandas

Raw data is almost never perfect. Columns have missing values. Rows contain errors. Some information is simply not relevant to the question you are trying to answer. **Data cleaning** is the process of fixing or removing those problems before you do any analysis.

Pandas gives you several methods to handle this. The four most common are:

| Method | What It Does |
|---|---|
| `df.fillna(value)` | Fills missing values with whatever you pass in — a number, a string, or a calculated value like the column mean |
| `df.dropna()` | Removes any row that contains at least one missing value |
| `df.drop(...)` | Removes entire rows or columns that you no longer need |
| `df.replace(old, new)` | Swaps one value for another across the DataFrame |

---

### Think Before You Clean

These methods change the shape and content of your data, so **the decision of which one to use matters**.

Before calling any of these, ask yourself:

- **Why is this value missing?** Was it never collected, or does the absence itself mean something?
- **How much data would I lose** if I drop all rows with missing values?
- **Would filling a missing value with the mean make sense** for this column, or would it distort the data?
- **Is this column actually useful** for what I am trying to answer, or is it noise?

There is no single right answer. Choosing how to clean your data is an **executive decision** — it shapes every result that comes after it, so it deserves careful thought.

In [20]:
# rent_df is already loaded — no import or read_csv needed


# ── df.fillna() ────────────────────────────────────────────────────────────
# Fill every missing value in the dataset with 0.
# Notice this returns a new DataFrame — rent_df itself is unchanged.

rent_df.fillna(0)

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,AL,1,METRO33860M33860,Autauga County,0,1,"Montgomery, AL MSA",100199999,58761,860,870,1016,1304,1537
1,AL,1,METRO19300M19300,Baldwin County,0,1,"Daphne-Fairhope-Foley, AL MSA",100399999,233420,1094,1200,1345,1692,2171
2,AL,1,NCNTY01005N01005,Barbour County,0,0,"Barbour County, AL",100599999,24877,576,693,776,1017,1068
3,AL,1,METRO13820M13820,Bibb County,0,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100799999,22251,1024,1155,1266,1583,1801
4,AL,1,METRO13820M13820,Blount County,0,1,"Birmingham-Hoover, AL HUD Metro FMR Area",100999999,59077,1024,1155,1266,1583,1801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4759,PR,72,METRO41980MM7440,Yabucoa Municipio,0,1,"San Juan-Guaynabo, PR HUD Metro FMR Area",7215199999,30313,559,572,663,868,1046
4760,PR,72,METRO38660M49500,Yauco Municipio,0,1,"Yauco, PR HUD Metro FMR Area",7215399999,33988,423,443,486,664,673
4761,VI,78,NCNTY78010N78010,St. Croix,0,0,"St. Croix Island, VI",7801099999,53234,1002,1023,1249,1504,1656
4762,VI,78,NCNTY78020N78020,St. John,0,0,"St. John Island, VI",7802099999,4197,1563,1578,1969,2362,2607
4763,VI,78,NCNTY78030N78030,St. Thomas,0,0,"St. Thomas Island, VI",7803099999,51181,1024,1189,1467,1759,1942

In [21]:
# ── df.dropna() ────────────────────────────────────────────────────────────
# Remove every row that has at least one missing value.
# Compare the shape before and after to see how many rows were dropped.

print("Rows before dropna:", rent_df.shape[0])
print("Rows after  dropna:", rent_df.dropna().shape[0])

Rows before dropna: 4764
Rows after  dropna: 1604

In [22]:
# ── df.drop() ──────────────────────────────────────────────────────────────
# Remove columns you do not need.
# Here we drop the FIPS code and the HUD area code — useful for HUD internally,
# but not relevant if we are only analyzing rent prices.
# axis=1 tells Pandas we are dropping columns (axis=0 would drop rows).

rent_df.drop(columns=["fips", "hud_area_code"])

,stusps,state,countyname,county_town_name,metro,hud_area_name,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,AL,1,Autauga County,NaN,1,"Montgomery, AL MSA",58761,860,870,1016,1304,1537
1,AL,1,Baldwin County,NaN,1,"Daphne-Fairhope-Foley, AL MSA",233420,1094,1200,1345,1692,2171
2,AL,1,Barbour County,NaN,0,"Barbour County, AL",24877,576,693,776,1017,1068
3,AL,1,Bibb County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",22251,1024,1155,1266,1583,1801
4,AL,1,Blount County,NaN,1,"Birmingham-Hoover, AL HUD Metro FMR Area",59077,1024,1155,1266,1583,1801
...,...,...,...,...,...,...,...,...,...,...,...,...
4759,PR,72,Yabucoa Municipio,NaN,1,"San Juan-Guaynabo, PR HUD Metro FMR Area",30313,559,572,663,868,1046
4760,PR,72,Yauco Municipio,NaN,1,"Yauco, PR HUD Metro FMR Area",33988,423,443,486,664,673
4761,VI,78,St. Croix,NaN,0,"St. Croix Island, VI",53234,1002,1023,1249,1504,1656
4762,VI,78,St. John,NaN,0,"St. John Island, VI",4197,1563,1578,1969,2362,2607
4763,VI,78,St. Thomas,NaN,0,"St. Thomas Island, VI",51181,1024,1189,1467,1759,1942

In [23]:
# ── df.replace() ───────────────────────────────────────────────────────────
# Swap one value for another throughout the DataFrame.
# The metro column uses 1 and 0 — replace those with readable labels
# so the data is easier to interpret at a glance.

rent_df.replace({1: "Metro", 0: "Non-Metro"})

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
0,AL,Metro,METRO33860M33860,Autauga County,NaN,Metro,"Montgomery, AL MSA",100199999,58761,860,870,1016,1304,1537
1,AL,Metro,METRO19300M19300,Baldwin County,NaN,Metro,"Daphne-Fairhope-Foley, AL MSA",100399999,233420,1094,1200,1345,1692,2171
2,AL,Metro,NCNTY01005N01005,Barbour County,NaN,Non-Metro,"Barbour County, AL",100599999,24877,576,693,776,1017,1068
3,AL,Metro,METRO13820M13820,Bibb County,NaN,Metro,"Birmingham-Hoover, AL HUD Metro FMR Area",100799999,22251,1024,1155,1266,1583,1801
4,AL,Metro,METRO13820M13820,Blount County,NaN,Metro,"Birmingham-Hoover, AL HUD Metro FMR Area",100999999,59077,1024,1155,1266,1583,1801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4759,PR,72,METRO41980MM7440,Yabucoa Municipio,NaN,Metro,"San Juan-Guaynabo, PR HUD Metro FMR Area",7215199999,30313,559,572,663,868,1046
4760,PR,72,METRO38660M49500,Yauco Municipio,NaN,Metro,"Yauco, PR HUD Metro FMR Area",7215399999,33988,423,443,486,664,673
4761,VI,78,NCNTY78010N78010,St. Croix,NaN,Non-Metro,"St. Croix Island, VI",7801099999,53234,1002,1023,1249,1504,1656
4762,VI,78,NCNTY78020N78020,St. John,NaN,Non-Metro,"St. John Island, VI",7802099999,4197,1563,1578,1969,2362,2607
4763,VI,78,NCNTY78030N78030,St. Thomas,NaN,Non-Metro,"St. Thomas Island, VI",7803099999,51181,1024,1189,1467,1759,1942

---

### 3.a Modification In Place

#### Your Changes Were Not Saved

Look back at every cleaning method we just called — `fillna`, `dropna`, `drop`, `replace`. Each one produced a result and Jupyter displayed it, but if you were to look at `rent_df` right now, it would be completely unchanged.

That is because by default, **Pandas methods return a new object — they do not modify the original**. The original DataFrame just sits there, untouched, until you explicitly tell Pandas to do otherwise.

---

### Two Ways to Make Your Changes Stick

#### Option 1 — Assign the result to a variable (recommended)

```python
clean_df = rent_df.dropna()
```

You are taking the result that Pandas hands back and storing it under a new name. From that point on, `clean_df` is your working copy and `rent_df` is still the original.

#### Option 2 — Use the `inplace=True` parameter

```python
rent_df.dropna(inplace=True)
```

This tells Pandas to apply the change directly to `rent_df` itself, overwriting it. No new variable is created.

---

### Why Option 1 Is Almost Always Better

Assigning to a new variable gives you two things at once:

1. **You keep the original.** If you make a mistake downstream, you can always go back to `rent_df` without reloading the file.
2. **The name tells a story.** A variable called `clean_df` or `metro_df` immediately signals to anyone reading your code that this is a modified version of the data — not the raw original.

Using `inplace=True` destroys the original without a safety net. If something goes wrong later, you have no fallback.

---

### When `inplace=True` Is Appropriate

There are situations where overwriting makes sense:

- You are working with a **very large dataset** and cannot afford to keep two copies of it in memory
- You are confident the transformation is correct and the original is already saved to disk (e.g., the CSV file is not going anywhere)
- You are at the **final step** of a cleaning pipeline and the intermediate versions have no further value

In [25]:
# ── Proof that rent_df is unchanged ────────────────────────────────────────
# Even after all the cleaning methods above, rent_df still has its original shape.

print("rent_df shape (should be unchanged):", rent_df.shape)
print("Missing values still present:\n")

print(rent_df.isna().sum())

rent_df shape (should be unchanged): (4764, 14)
Missing values still present:

stusps                 0
state                  0
hud_area_code          0
countyname             0
county_town_name    3160
metro                  0
hud_area_name          0
fips                   0
pop2023                0
fmr_0                  0
fmr_1                  0
fmr_2                  0
fmr_3                  0
fmr_4                  0
dtype: int64

In [26]:
# ── Option 1: Assign to a new variable (recommended) ──────────────────────
# Drop missing rows and store the result under a new name.
# rent_df remains the original — clean_df is our working copy.

clean_df = rent_df.dropna()

print("rent_df rows  (original):", len(rent_df))
print("clean_df rows (modified):", len(clean_df))

rent_df rows  (original): 4764
clean_df rows (modified): 1604

In [27]:
# ── Option 2: inplace=True ─────────────────────────────────────────────────
# Here we work on a copy so we do not destroy rent_df for the rest of the notebook.
# In a real scenario where you intentionally want to overwrite, you would call
# this directly on your DataFrame — no copy needed.

demo_df = rent_df.copy()

print("demo_df rows before dropna:", len(demo_df))

demo_df.dropna(inplace=True)

print("demo_df rows after  dropna:", len(demo_df))
print()
print("rent_df is still untouched:", len(rent_df), "rows")

demo_df rows before dropna: 4764
demo_df rows after  dropna: 1604

rent_df is still untouched: 4764 rows

---

## 4. Indexing / Filtering Data

Once your data is loaded, you rarely want to work with the entire DataFrame at once. You will usually need to **pull out specific columns or rows** — that is what indexing is for.

There are three core ways to index into a Pandas DataFrame:

---

### 4.1 — Select a Single Column

Pass one column name inside single brackets. This returns a **Series**.

```python
rent_df["fmr_2"]
```

---

### 4.2 — Select Multiple Columns

Pass a **list** of column names inside the brackets. This returns a **DataFrame**.

```python
rent_df[["stusps", "countyname", "fmr_2"]]
```

The double brackets are not a typo — the outer brackets are the indexing operator, the inner brackets are the Python list.

---

### 4.3 — Select by Row and Column Using `.loc`

`.loc` lets you target a specific **row label** and **column name** at the same time.

```python
rent_df.loc[row_label, "column_name"]
```

By default, Pandas uses a numeric index (0, 1, 2, …) as row labels, so you pass the row number. You can also use a slice to grab a range of rows.

In [28]:
# ── 4.1 Single column → returns a Series ──────────────────────────────────
rent_df["fmr_2"]

0       1016
1       1345
2        776
3       1266
4       1266
        ...
4759     663
4760     486
4761    1249
4762    1969
4763    1467
Name: fmr_2, Length: 4764, dtype: int64

In [29]:
# ── 4.2 Multiple columns → returns a DataFrame ────────────────────────────
rent_df[["stusps", "countyname", "fmr_1", "fmr_2", "fmr_3"]]

     stusps         countyname  fmr_1  fmr_2  fmr_3
0        AL     Autauga County    870   1016   1304
1        AL     Baldwin County   1200   1345   1692
2        AL     Barbour County    693    776   1017
3        AL        Bibb County   1155   1266   1583
4        AL      Blount County   1155   1266   1583
...     ...                ...    ...    ...    ...
4759     PR  Yabucoa Municipio    572    663    868
4760     PR    Yauco Municipio    443    486    664
4761     VI          St. Croix   1023   1249   1504
4762     VI           St. John   1578   1969   2362
4763     VI         St. Thomas   1189   1467   1759

[4764 rows x 5 columns]

In [34]:
# ── 4.3 .loc — target a specific row and column ───────────────────────────

# A single cell: row 0, column "hud_area_name"
print("Single cell with .loc:")
print(rent_df.loc[0, "hud_area_name"])

Single cell with .loc:
Montgomery, AL MSA

In [35]:
# A single full row
print("Full row 0:")
print(rent_df.loc[0])

Full row 0:
stusps                              AL
state                                1
hud_area_code         METRO33860M33860
countyname              Autauga County
county_town_name                   NaN
metro                                1
hud_area_name       Montgomery, AL MSA
fips                         100199999
pop2023                          58761
fmr_0                              860
fmr_1                              870
fmr_2                             1016
fmr_3                             1304
fmr_4                             1537
Name: 0, dtype: object

In [36]:
# A slice of rows, specific columns
print("Rows 0 through 4, selected columns:")
rent_df.loc[0:4, ["stusps", "countyname", "fmr_2"]]

Rows 0 through 4, selected columns:

  stusps      countyname  fmr_2
0     AL  Autauga County   1016
1     AL  Baldwin County   1345
2     AL  Barbour County    776
3     AL     Bibb County   1266
4     AL   Blount County   1266

---

## 4.a Boolean Filters

### What Is a Boolean Filter?

A **boolean filter** is a condition you write that evaluates every row in the DataFrame and produces an array of `True` and `False` values — one result per row.

For example:

```python
rent_df["fmr_2"] > 2000
```

This does not return a number. It returns a **Series of True/False values** — `True` for every row where the 2-bedroom rent is above $2,000, and `False` for every row where it is not.

---

### Step 1 — Create the boolean expression

```python
mask = rent_df["fmr_2"] > 2000
```

`mask` is now a Series that looks like this:

```
0      False
1      False
2       True
3      False
...
```

---

### Step 2 — Plug the mask into the DataFrame brackets

```python
rent_df[mask]
```

Pandas goes through every row. If the mask value for that row is `True`, the row is kept. If it is `False`, the row is dropped. The result is a filtered DataFrame containing **only the rows where your condition was met**.

You can also write it in one line without the intermediate variable:

```python
rent_df[rent_df["fmr_2"] > 2000]
```

Both approaches produce the exact same result — the two-step version with a named mask is simply easier to read.

In [37]:
# ── Step 1: See the boolean array on its own ──────────────────────────────
# Every row gets a True or False depending on the condition.

mask = rent_df["fmr_2"] > 2000

mask

0       False
1       False
2       False
3       False
4       False
        ...
4759    False
4760    False
4761    False
4762    False
4763    False
Name: fmr_2, Length: 4764, dtype: bool

In [38]:
# ── Step 2: Plug the mask into the DataFrame ──────────────────────────────
# Only rows where mask == True are returned.

rent_df[mask]

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
68,AK,2,NCNTY02016N02016,Aleutians West Census Area,NaN,0,"Aleutians West Census Area, AK",201699999,5219,1571,1670,2191,2652,2901
82,AK,2,NCNTY02150N02150,Kodiak Island Borough,NaN,0,"Kodiak Island Borough, AK",215099999,13065,1431,1581,2075,2488,2747
187,CA,6,METRO41860MM5775,Alameda County,NaN,1,"Oakland-Fremont, CA HUD Metro FMR Area",600199999,1663823,2142,2385,2912,3724,4413
193,CA,6,METRO41860MM5775,Contra Costa County,NaN,1,"Oakland-Fremont, CA HUD Metro FMR Area",601399999,1162648,2142,2385,2912,3724,4413
195,CA,6,METRO40900M40900,El Dorado County,NaN,1,"Sacramento--Roseville--Arden-Arcade, CA HUD Me...",601799999,191713,1748,1832,2255,3002,3460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4472,VA,51,METRO47900M47900,Manassas city,NaN,1,"Washington-Arlington-Alexandria, DC-VA-MD HUD ...",5168399999,42620,1953,2015,2246,2835,3332
4473,VA,51,METRO47900M47900,Manassas Park city,NaN,1,"Washington-Arlington-Alexandria, DC-VA-MD HUD ...",5168599999,17123,1953,2015,2246,2835,3332
4507,WA,53,METRO42660MM7600,King County,NaN,1,"Seattle-Bellevue, WA HUD Metro FMR Area",5303399999,2254371,2074,2146,2501,3272,3847
4508,WA,53,METRO14740M14740,Kitsap County,NaN,1,"Bremerton-Silverdale-Port Orchard, WA MSA",5303599999,275411,1400,1548,2031,2676,2941
4521,WA,53,METRO42660MM7600,Snohomish County,NaN,1,"Seattle-Bellevue, WA HUD Metro FMR Area",5306199999,828337,2074,2146,2501,3272,3847

In [39]:
# ── One-liner version — same result, no intermediate variable ──────────────
rent_df[rent_df["fmr_2"] > 2000]

,stusps,state,hud_area_code,countyname,county_town_name,metro,hud_area_name,fips,pop2023,fmr_0,fmr_1,fmr_2,fmr_3,fmr_4
68,AK,2,NCNTY02016N02016,Aleutians West Census Area,NaN,0,"Aleutians West Census Area, AK",201699999,5219,1571,1670,2191,2652,2901
82,AK,2,NCNTY02150N02150,Kodiak Island Borough,NaN,0,"Kodiak Island Borough, AK",215099999,13065,1431,1581,2075,2488,2747
187,CA,6,METRO41860MM5775,Alameda County,NaN,1,"Oakland-Fremont, CA HUD Metro FMR Area",600199999,1663823,2142,2385,2912,3724,4413
193,CA,6,METRO41860MM5775,Contra Costa County,NaN,1,"Oakland-Fremont, CA HUD Metro FMR Area",601399999,1162648,2142,2385,2912,3724,4413
195,CA,6,METRO40900M40900,El Dorado County,NaN,1,"Sacramento--Roseville--Arden-Arcade, CA HUD Me...",601799999,191713,1748,1832,2255,3002,3460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4472,VA,51,METRO47900M47900,Manassas city,NaN,1,"Washington-Arlington-Alexandria, DC-VA-MD HUD ...",5168399999,42620,1953,2015,2246,2835,3332
4473,VA,51,METRO47900M47900,Manassas Park city,NaN,1,"Washington-Arlington-Alexandria, DC-VA-MD HUD ...",5168599999,17123,1953,2015,2246,2835,3332
4507,WA,53,METRO42660MM7600,King County,NaN,1,"Seattle-Bellevue, WA HUD Metro FMR Area",5303399999,2254371,2074,2146,2501,3272,3847
4508,WA,53,METRO14740M14740,Kitsap County,NaN,1,"Bremerton-Silverdale-Port Orchard, WA MSA",5303599999,275411,1400,1548,2031,2676,2941
4521,WA,53,METRO42660MM7600,Snohomish County,NaN,1,"Seattle-Bellevue, WA HUD Metro FMR Area",5306199999,828337,2074,2146,2501,3272,3847

---

## Exercises

Use the `rent_df` DataFrame to answer each question below. Write your code in the cell beneath each question.

---

**Question 1**

Display the first **12 rows** of `rent_df`.

In [ ]:
# Question 1

**Question 2**

Use a single method call to print a full overview of `rent_df` — including each column's name, its data type, and how many non-null values it contains.

In [ ]:
# Question 2

**Question 3**

Create a boolean filter and use it to display only the rows where the **1-bedroom fair market rent (`fmr_1`) is greater than $1,500**.

In [ ]:
# Question 3

**Question 4**

Create a boolean filter and use it to display only the rows where the **state abbreviation (`stusps`) is equal to `"NY"`**.

In [ ]:
# Question 4

**Question 5**

Create a boolean filter that combines **two conditions**:
- The area is a metro area (`metro == 1`)
- The 2-bedroom fair market rent (`fmr_2`) is greater than $3,000

Display only the rows where **both** conditions are true.

In [ ]:
# Question 5

---

## Answers

> Try each question on your own before reading below.

---

**Answer 1**

```python
rent_df.head(12)
```

`.head()` accepts an optional integer argument. Passing `12` overrides the default of 5.

---

**Answer 2**

```python
rent_df.info()
```

`.info()` is the one method that prints column names, non-null counts, and data types all together in a single call. Note that unlike most Pandas methods, `.info()` prints directly to the console — it does not return a value for Jupyter to display.

---

**Answer 3**

```python
mask = rent_df["fmr_1"] > 1500
rent_df[mask]
```

Or as a one-liner:

```python
rent_df[rent_df["fmr_1"] > 1500]
```

`fmr_1` is the 1-bedroom fair market rent column. The condition produces a Series of True/False values, and plugging it into the brackets keeps only the True rows.

---

**Answer 4**

```python
mask = rent_df["stusps"] == "NY"
rent_df[mask]
```

Or as a one-liner:

```python
rent_df[rent_df["stusps"] == "NY"]
```

Notice the **double equals sign** `==` for comparison. A single `=` is assignment — it would throw an error here.

---

**Answer 5**

```python
mask = (rent_df["metro"] == 1) & (rent_df["fmr_2"] > 3000)
rent_df[mask]
```

Or as a one-liner:

```python
rent_df[(rent_df["metro"] == 1) & (rent_df["fmr_2"] > 3000)]
```

Two things to notice:
- Each individual condition must be wrapped in its own **parentheses** before combining them
- Use `&` for AND, not the Python keyword `and` — Pandas requires the bitwise operator when working with Series